---
swagger: 2.0
info:
  title: Auto Diagram
  description:
  version: 1.0.0
paths:
  /diagrams/high-level:
    post:
      summary: Generate a new diagram from the supplied parameters.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Stack'
      responses:
        200:
          description: Diagram created. Response body will contain the diagram image.
definitions:
  Stack:
    title: Root Type for Stack
    description: The root of the Stack type's schema.
    type: object
    properties:
      organization:
        type: string
      hosting:
        type: string
      sourceControl:
        type: string
      collaborationTools:
        type: array
        items:
          type: string
      environments:
        type: array
        items:
          type: string
      appContainers:
        type: array
        items:
          type: string
      testLibraries:
        type: array
        items:
          type: string
